package openeja.bo.javadb;

import openeja.annotation.*;
import openeja.orm.Entity;

@Table(name = "departments")
public class Departments extends Entity {

	@Id
	@AutoGenerated
	@Column(name = "id", type = "int")
	private int id;

	@Column(name = "department_name", type = "varchar", length = "256")
	private String departmentName;

	public Departments(){
		this.id = 0;
		this.departmentName = "";

	}
	public void setId(int id){
		this.id = id;
	}
	public int getId(){
		return id;
	}
	public void setDepartmentName(String departmentName){
		this.departmentName = departmentName;
	}
	public String getDepartmentName(){
		return departmentName;
	}
}
