package openeja.bo.javadb;

import openeja.annotation.*;
import openeja.orm.Entity;

@Table(name = "employees")
public class Employees extends Entity {

	@Id
	@AutoGenerated
	@Column(name = "id", type = "int")
	private int id;

	@Column(name = "first_name", type = "varchar", length = "50")
	private String firstName;

	@Column(name = "last_name", type = "varchar", length = "50")
	private String lastName;

	@Column(name = "email", type = "varchar", length = "50")
	private String email;

	@ManyToOne
	@Column(name = "departments_id", type = "int")
	private int departmentsId;

	@ManyToOne
	public Departments departments;


	public Employees(){
		this.id = 0;
		this.firstName = "";
		this.lastName = "";
		this.email = "";
		this.departmentsId = 0;
		this.departments = new Departments();

	}
	public void setId(int id){
		this.id = id;
	}
	public int getId(){
		return id;
	}
	public void setFirstName(String firstName){
		this.firstName = firstName;
	}
	public String getFirstName(){
		return firstName;
	}
	public void setLastName(String lastName){
		this.lastName = lastName;
	}
	public String getLastName(){
		return lastName;
	}
	public void setEmail(String email){
		this.email = email;
	}
	public String getEmail(){
		return email;
	}
	public void setDepartmentsId(int departmentsId){
		this.departmentsId = departmentsId;
	}
	public int getDepartmentsId(){
		return departmentsId;
	}
}
