package OpenEJA.BO.Javadb;

import OpenEJA.Annotation.*;
import OpenEJA.ORM.Entity;

@Table(name = "employees")
public class Employees extends Entity {

	@Id
	@AutoGenerated
	@Column(name = "id", type = "int")
	public Integer id;

	@Column(name = "first_name", type = "varchar", length = "50")
	public String firstName;

	@Column(name = "last_name", type = "varchar", length = "50")
	public String lastName;

	@Column(name = "email", type = "varchar", length = "50")
	public String email;

	public Employees(){
		this.id = 0;
		this.firstName = "";
		this.lastName = "";
		this.email = "";

	}
}
