package openeja.bo.javadb;

import openeja.annotation.*;
import openeja.orm.Entity;

@Table(name = "test")
public class Test extends Entity {

	@Id
	@AutoGenerated
	@Column(name = "id", type = "int")
	private int id;

	@Column(name = "name", type = "varchar", length = "50")
	private String name;

	@ManyToOne
	@Column(name = "email", type = "varchar", length = "256")
	private String email;

	@Column(name = "mobile", type = "varchar", length = "15")
	private String mobile;

	@Column(name = "addresss", type = "text", length = "65535")
	private String addresss;

	@Column(name = "created_date", type = "datetime")
	private String createdDate;

	@Column(name = "price", type = "double")
	private double price;

	public Test(){
		this.id = 0;
		this.name = "";
		this.email = "";
		this.mobile = "";
		this.addresss = "";
		this.createdDate = "2016/02/02 01:47:52";
		this.price = 0.0;

	}
	public void setId(int id){
		this.id = id;
	}
	public int getId(){
		return id;
	}
	public void setName(String name){
		this.name = name;
	}
	public String getName(){
		return name;
	}
	public void setEmail(String email){
		this.email = email;
	}
	public String getEmail(){
		return email;
	}
	public void setMobile(String mobile){
		this.mobile = mobile;
	}
	public String getMobile(){
		return mobile;
	}
	public void setAddresss(String addresss){
		this.addresss = addresss;
	}
	public String getAddresss(){
		return addresss;
	}
	public void setCreatedDate(String createdDate){
		this.createdDate = createdDate;
	}
	public String getCreatedDate(){
		return createdDate;
	}
	public void setPrice(double price){
		this.price = price;
	}
	public double getPrice(){
		return price;
	}
}
